packages:
  - apps/*
  - packages/*

minimumReleaseAgeExclude:
  - '@kubohiroya/turbowarp-aframe@0.3.0 || 0.4.0 || 0.5.0'
  - '@kubohiroya/turbowarp-asset-manager@0.16.0'
  - '@kubohiroya/turbowarp-camera-source@0.5.0 || 0.6.0 || 0.10.0 || 0.11.0 || 0.12.0 || 0.13.0'
  - '@kubohiroya/turbowarp-diagnostic-overlay@0.4.0'
  - '@kubohiroya/turbowarp-realtime-motion-capture@0.1.0 || 0.2.0 || 0.2.1 || 0.3.0 || 0.4.0 || 0.5.0'
  - '@kubohiroya/turbowarp-webrtc@0.3.0 || 0.4.0'
  - '@kubohiroya/turbowarp-webrtc-qrcode-pairing@0.1.0 || 0.2.0 || 0.2.1 || 0.2.2 || 0.2.3'
  - '@kubohiroya/turbowarp-jsqr@0.4.0'
  - '@kubohiroya/qrcode-structured-append@0.1.0'
  - '@kubohiroya/turbowarp-yaml-json@0.3.0'
  - '@kubohiroya/turbowarp-time-space-sync@0.2.0'
  - '@kubohiroya/turbowarp-title-menu@0.2.0 || 0.2.1 || 0.2.2'
  - '@kubohiroya/turbowarp-local-preview@0.1.1'

onlyBuiltDependencies: []
