import { servedPoseModelFiles } from '../packages/app-shell/pose-model-files.ts';
import { execFile } from 'node:child_process';
import { access, writeFile } from 'node:fs/promises';
import { promisify } from 'node:util';

import {
  readJson,
  repositoryRoot,
  type LocalHostConfig,
} from './repository-config.ts';

const executeFile = promisify(execFile);
const config = await readJson<LocalHostConfig>('config/local-host.json');

/**
 * Cross-compilation targets, or the host platform when none is named.
 *
 * `bun build --compile` ad-hoc signs what it produces, which is what macOS on Apple Silicon requires
 * to run an executable at all. It does not remove the Gatekeeper warning a downloaded file carries.
 */
const targets = process.argv
  .slice(2)
  .filter((argument) => argument.startsWith('--target='));

async function requireBun(): Promise<string> {
  const { stdout } = await executeFile('bun', ['--version']).catch(() => ({
    stdout: '',
  }));
  if (stdout.trim().length === 0) {
    throw new Error(
      'bun is required to build the venue binary. Install it from https://bun.sh and try again.',
    );
  }
  return stdout.trim();
}

const version = await requireBun();
console.log(`bun ${version}`);

const failures: string[] = [];

for (const [app, { port, title, lensCalibration }] of Object.entries(
  config.apps,
)) {
  const distUrl = new URL(`apps/${app}/dist/`, repositoryRoot);
  const playerName = `${app}-player.html`;
  const playerUrl = new URL(playerName, distUrl);
  if (
    !(await access(playerUrl).then(
      () => true,
      () => false,
    ))
  ) {
    failures.push(
      `${app}: run \`pnpm run build:player\` first (${playerName} is missing)`,
    );
    continue;
  }

  /**
   * The entry is generated rather than committed because everything in it is already decided
   * elsewhere: the port and title in config/local-host.json, the player next to it. Writing it by
   * hand would create a third place for the port to disagree with itself.
   */
  const entryUrl = new URL(`${app}-entry.ts`, distUrl);
  const calibrationName = `${app}-lens-calibration-player.html`;
  const withCalibration =
    lensCalibration !== undefined &&
    (await access(new URL(calibrationName, distUrl)).then(
      () => true,
      () => false,
    ));
  if (lensCalibration !== undefined && !withCalibration) {
    console.warn(
      `${app}: no lens calibration player, so the binary cannot open one`,
    );
  }
  /**
   * A shell built with TWRMC_POSE_MODEL=local asks the host for the MoveNet model, so the binary
   * carries the pinned files — each embedded with `type: 'file'` and served by its route.
   */
  const modelFiles = Object.entries((await servedPoseModelFiles(app)) ?? {});
  const modelImports = modelFiles
    .map(
      ([, path], index) =>
        `import poseModelFile${index} from ${JSON.stringify(path)} with {type: 'file'};\n`,
    )
    .join('');
  const modelRoutes =
    modelFiles.length === 0
      ? ''
      : `,\n  files: {\n${modelFiles
          .map(
            ([route], index) =>
              `    ${JSON.stringify(route)}: poseModelFile${index},\n`,
          )
          .join('')}  }`;
  await writeFile(
    entryUrl,
    `// Generated by scripts/build-binary.ts. Do not edit.\n` +
      `import player from './${playerName}' with {type: 'text'};\n` +
      (withCalibration
        ? `import lensCalibrationPlayer from './${calibrationName}' with {type: 'text'};\n`
        : '') +
      modelImports +
      `import {runLocalHostCli} from '../../../packages/local-host/src/cli.ts';\n\n` +
      `const outcome = await runLocalHostCli({\n` +
      `  app: ${JSON.stringify(app)},\n` +
      `  title: ${JSON.stringify(title)},\n` +
      `  port: ${port},\n` +
      `  player${withCalibration ? ',\n  lensCalibrationPlayer' : ''}${modelRoutes}\n` +
      `});\n` +
      `// A refused start has to reach the shell, or a script cannot tell it did not run.\n` +
      `process.exitCode = outcome.code;\n`,
  );

  for (const target of targets.length > 0 ? targets : ['']) {
    const suffix =
      target === '' ? '' : `-${target.slice('--target=bun-'.length)}`;
    const outfile = new URL(`${app}${suffix}`, distUrl);
    const args = [
      'build',
      '--compile',
      ...(target === '' ? [] : [target]),
      '--outfile',
      outfile.pathname,
      entryUrl.pathname,
    ];
    const { stderr } = await executeFile('bun', args, {
      maxBuffer: 32 * 1024 * 1024,
    }).catch((error: { stderr?: string }) => ({
      stderr: error.stderr ?? 'bun build failed',
    }));
    const built = await access(outfile).then(
      () => true,
      () => false,
    );
    if (!built) {
      failures.push(
        `${app}${suffix}: ${stderr.trim().split('\n').at(-1) ?? 'bun build failed'}`,
      );
      continue;
    }
    console.log(`${app}${suffix}: built`);
  }
}

if (failures.length > 0) {
  console.error(failures.map((failure) => `- ${failure}`).join('\n'));
  process.exitCode = 1;
}
